### PR TITLE
Fix for afterLastStep function call in Dialog/proceed.

### LINKED ISSUE #17: Dialog-proceed-afterAllStep wrong place
Hello. I'm very interested to use this package, so i explore it in details to understand it. As i'm new to github i have no experience in PRs and merging, so i decided to write here. Please, forgive for that.

I think there is a wrong place for 
```php
if ($this->isEnd()) {
    $this->afterAllStep($update);
    return;
}
```
in the beginning of proceed function in Dialog.php file. 

Imagine, you are at the last step of dialog. In Dialog:proceed $this->isEnd returns false, then all the things are done and dialog steps counter becomes +1 in the end of function. After that flow appears in DialogManager:proceed right before the code
```php
if ($dialog->isEnd()) {
    $this->forgetDialogState($dialog);
}
```
So this dialog will be deleted from Store here. So in this example afterAllStep didn't work at the beginning, because there was not the end of dialog. But it will never work later, because dialog was deleted. So i think in proceed function of Dialog.php the code 
```php
if ($this->isEnd()) {
    $this->afterAllStep($update);
    return;
}
```
should be transferred to the place right after 
```php
 ++$this->next;
```
in the end of file.

### PR DESCRIPTION
**Pull request by dimaodnokoz**
Closes #17

 Fix for afterLastStep function call in Dialog/proceed. afterProceedJumpToIndex took into account = afterLastStep should be called if flow jumps from the last step. PassiveTestDialog updated to test this. isLastStep added because isEnd can not be used in this case.

### CODE REVIEW

File: src/Dialog.php [hunk 1]
```diff
@@ -222,6 +221,12 @@ final public function isStart(): bool
         return $this->next === 0;
     }
 
+    /** Check if Dialog on the last step */
+    final public function isLastStep(): bool
```
Comment (lptn) [inline src/Dialog.php:225]: BTW: do you have any meaningful use-cases for this method? I usually try to minimize creation of public methods to avoid BC breaks in the future.

File: src/Dialog.php [hunk 2]
```diff
@@ -129,6 +124,10 @@ final public function proceed(Update $update): void
             throw new InvalidDialogStep('Unknown format of the step.');
         }
 
+        if ($this->isLastStep()) {
+            $this->afterLastStep($update);
+        }
```
Comment (lptn) [inline src/Dialog.php:129]: 👍

File: tests/TestDialogs/PassiveTestDialog.php [hunk 3]
```diff
@@ -29,6 +29,7 @@ public function step2(Update $update): void
 
     public function step3(Update $update): void
     {
+        $this->jump("step2");
```
Comment (lptn) [inline tests/TestDialogs/PassiveTestDialog.php:32]: Honestly, I'm not really happy about making this test class specific for this case. It will make this test Tet class full of magic and not really reusable for further changes. is it safe to remove this line?

**Review by lptn — CHANGES_REQUESTED** [review]
@dimaodnokoz 
looks great! Thank for the fix 💪 🚀 

I have some questions, can you please take a look and reply to them before the merge?


I see how this package finally becoming usable - great work!


I also contributed a bit to it and make example dialog more advanced: https://github.com/koot-labs/telegram-bot-dialogs/blob/master/src/Dialogs/HelloExampleDialog.php

I hope it will make it easy to use this package and write other Dialogs for new comers.

File: src/Dialog.php (hunk 1 above)
Comment (dimaodnokoz) [reply src/Dialog.php:225]: I use it just for fix, because isEnd is not useful there. We may just use the check $this->next == count($this->steps) - 1; at that place instead of function, but it seems not good and clear. Probably it's better to make this function private and that's all.

File: tests/TestDialogs/PassiveTestDialog.php (hunk 3 above)
Comment (dimaodnokoz) [reply tests/TestDialogs/PassiveTestDialog.php:32]: This line is for test of afterLastStep call, when dialog jumps from the last step. In this case afterLastStep should be also called, i think (BTW: I do not imagine the case, where beforeFirstStep and/or afterLastStep functions may be used, so this call is still a question). I agree with your conclusion. But, we can remove this line only with make of another test. What may it be?
1) Ideally to do like in DialogTest.php, where you initiate dialog instance with steps at a place. I tried this approach, but failed. Error: can not serialize object by anonymous user (smth like that) when "activate" function called. I didn't find solution for that.
2) Also it is the way to make FakeDialog file like FakeBot for similar small tests (and add cases there for different tests), but i didn't understand how to add function there.
3) Making another test dialog just for this test seems bad.

BTW: I build telegram bots from 2018. It is like my main job. But i do it with some no code service (Pipe.bot - like Manychat or Chatfuel) with adding of php scripts for advanced tasks. Now i'd like to work without any no code service. So i'm here and very interested in some packages like this and sdk) I want to say, i have a lot of experience about dialog cases and tg api, but with notice, that it was partially with nocode service. As about my php knowledge. I integrated almost all Ukrainian payment systems to my chatbots, using plain php and webhooks. I'm like juniour, but with strong university dev background of 2001-2007 ))) Probably it will be more quick and comfortable to communicate in tg? It will be for me for sure. My contact: @DimaOdnokoz there.

File: src/Dialog.php (hunk 1 above)
Comment (lptn) [reply src/Dialog.php:225]: let's start from private. If someone will need it public - they can create a PR.

File: tests/TestDialogs/PassiveTestDialog.php (hunk 3 above)
Comment (lptn) [reply tests/TestDialogs/PassiveTestDialog.php:32]: ok, let's merge is as it, I'll reply later. Green CI is more important than clean tests
